### ISSUE TITLE
Compilation error with custom operator==

### ISSUE THREAD

**Issue by WarShoe** [boost-ext/ut#504]
The following code does not compile:

```#include "ut.hpp"
using namespace boost::ut;

struct S {
    bool operator == (const S &) const {return false;}
};

int main(){
    S s;
    "compare"_test = [&] {
        expect(that% s==s);
    };
}
```

## Specifications

  - Version: BOOST_UT_VERSION 1'1'9
  - Platform: Ubuntu 20.04.4 LTS
  - Subsystem:

**Comment by 80Ltrumpet** [comment]
Based on the compilation errors, ut requires types that participate in assertion operations to be streamable. Adding the following causes the example to compile, and a somewhat cryptic `FAILED [S == S]` message will print upon execution.

```c++
// std::ostream is preferred over auto, if importing/including iostream.
auto& operator<<(auto& stream, const S&) { return os << "S"; }
```

The question is whether this is intended. Based on my experience with other C++ testing frameworks (e.g., GoogleTest), I assume the answer is yes, since there is no way for the assertion printer to know how to represent your custom type's value otherwise.

**Comment by WarShoe** [comment]
ok, I think it makes sense. Thanks!
